model:
    bagging_seed: 42
    boosting_type: gbdt
    categorical_column:
      - 0
    data_random_seed: 42
    drop_seed: 42
    feature_fraction: 0.5
    feature_fraction_seed: 42
    lambda_l1: 0.5
    lambda_l2: 1.0
    learning_rate: 0.05
    max_bin: 100
    max_depth: -1
    min_data_in_leaf: 500
    n_jobs: -1
    objective: rmse
    seed: 42
    subsample: 0.72
    subsample_freq: 4
    verbose: -1

trainer:
    num_boost_round: 5000
    verbose_eval: 250
