model:
    n_categories:
      - 128
      - 32768
    dropout_num: 0.0
    hidden: 50
    emb_dim: 10
    dropout_id: 0.2
    bn: False

trainer:
    epochs: 30
    lr: 0.001
    batch_size: 128
    device: cpu

